### ISSUE TITLE
Schedule and Progress Tracking

### ISSUE THREAD

**Issue by nealfennimore** [nealfennimore/wgu-android-student-app#5]
Create a scheduler and progress tracking application as part of your mobile application from part A.

Note: This can be the implementation of part A.

Include the following implementation requirements in the application from part C. Be sure your application is a minimum version 4.0 mobile application:
- [x] an ArrayList
- [x] an intent
- [x] navigation capability between multiple screens using activity
- [x] three activities
- [x] events (e.g., a click event)
- [x] the ability to work in portrait and landscape layout
- [x] interactive capability (e.g., the ability to accept and act upon user input)
- [x] a database to store and retrieve application data
- [x] an application title and an icon
- [x] notifications or alerts
- [x] the use of both declarative and programmatic methods to create a user interface

Include the following interface requirements in the application from part C:
- [x] the ability to scroll vertically
- [x] an action bar
- [x] two layouts
- [x] input controls
- [x] buttons
